enum Types {
    FETCH_CAKES = 'FETCH_CAKES',
    RECEIVED_CAKES = 'RECEIVED_CAKES',
    FETCH_CAKES_FAILED = 'FETCH_CAKES_FAILED',

    FETCH_CAKE = 'FETCH_CAKE',
    RECEIVED_CAKE = 'RECEIVED_CAKE',
    FETCH_CAKE_FAILED = 'FETCH_CAKE_FAILED',

    ADD_CAKE = 'ADD_CAKE',
    CAKE_ADDED = 'CAKE_ADDED',
    ADD_CAKE_FAILED = 'ADD_CAKE_FAILED'
}

export default Types;
